services:
  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb config_rs/${MONGODB_CONFIGSVR1_CONTAINER_NAME}:27017,${MONGODB_CONFIGSVR2_CONTAINER_NAME}:27017,${MONGODB_CONFIGSVR3_CONTAINER_NAME}:27017 --port 27017 --bind_ip_all
    ports:
      - 30000:27017
    volumes:
      - ./scripts:/scripts
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongos:27017"
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: 'admin'
    depends_on:
      - mongos