networks:
  default:
    name: "movie-hub"

volumes:
  movie-hub-postgres-keycloak:


services:
  postgres-keycloak:
    image: 'postgres:17.0'
    container_name: 'movie-hub-postgres-keycloak'
    ports:
      - '5432:5432'
    volumes:
      - movie-hub-postgres-keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_USER_PASSWORD}
      POSTGRES_USER: ${POSTGRES_KEYCLOAK_USER}
      POSTGRES_DB: ${POSTGRES_KEYCLOAK_DB}
  
  keycloak:
    image: 'my-keycloak-kafka:new-local'
    build:
      context: ./keycloak/
    container_name: 'movie-hub-keycloak'
    ports:
      - "8080:8080"
    command:
      [
        'start-dev',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
        '--import-realm',
        '--log-console-color=true'
      ]
#    volumes:
#      - ./keycloak/configuration/:/opt/keycloak/data/import/
    environment:
      KC_DB: 'postgres'
      KC_DB_URL_HOST: 'movie-hub-postgres-keycloak'
      KC_DB_URL_DATABASE: ${POSTGRES_KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_USER_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_USER_PASSWORD}
      KAFKA_TOPIC: movie-hub.keycloak-events
      KAFKA_CLIENT_ID: keycloak
      KAFKA_EVENTS: REGISTER
      KAFKA_BOOTSTRAP_SERVERS: movie-hub-kafka-broker:29092
      KEYCLOAK_IMPORT: ./keycloak/configuration/movie-hub-realm-export.json
    depends_on:
      - postgres-keycloak
  
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.6.0'
    container_name: 'movie-hub-zookeeper'
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka-broker:
    image: 'confluentinc/cp-kafka:7.6.0'
    container_name: 'movie-hub-kafka-broker'
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://movie-hub-kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
  
  
  kafka-ui:
    container_name: 'movie-hub-kafka-ui'
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - 8082:8080
    depends_on:
      - kafka-broker
      - keycloak
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:29092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: keycloak-events-outbox
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://movie-hub-kafka-connect:8083
      
      
  jaeger:
    image: 'jaegertracing/all-in-one'
    container_name: 'movie-hub-jaeger'
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
  
  
  
#  api:
#    build:
#      context: ./..
#      dockerfile: docker/Dockerfile
#    container_name: 'movie-hub-api'
#    image: 'my-movie-hub:new-local'
#    ports:
#      - '7189:8080'
#    environment:
##      ASPNETCORE_ENVIRONMENT: 'Development'
#      ASPNET_URLS: 'http://0.0.0.0:7189'
##      ConnectionStrings__EnglishHubDbContext: 'Host=postgres;User Id=shombal;Password=1111;Database=english_hub;Port=5432'
##      ConnectionStrings__Logs: 'http://loki:3100'
##      ConnectionStrings__Tracing: 'http://jaeger:4318/v1/traces'